# Dependencies
markdown:         redcarpet
highlighter:      pygments

exclude:          ['.asset_pipeline', 'deploy.sh', 'server-script.sh']

# Permalinks
#permalink:        pretty
permalink:        /blog/:title

# Setup
title:            Fnaf Coloring Pages
description:      "Free And Printable Fnaf Coloring Pages For Kids"

author:
  name:           'Thomas Vinh'
  url:            http://autoizipro.com/
  email:          thomasthevinh@gmail.com
